services:
  webserver:
    build:
      context: .
      dockerfile: ./frankenphp/Dockerfile
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      PHP_IDE_CONFIG: 'serverName=localhost'
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-app}
      DB_USERNAME: ${DB_USERNAME:-app}
      DB_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    depends_on:
      database:
        condition: service_healthy

  database:
    ports:
      - ${DATABASE_PORT:-5432}:5432

  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
      target: node_dev
    image: ${IMAGES_PREFIX:-}app-node
    environment:
      APP_URL: https://${SERVER_NAME:-localhost}
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      webserver:
        condition: service_healthy

volumes:
  database_data: