# Production environment override
services:
  webserver:
    build:
      context: .
      dockerfile: ./frankenphp/Dockerfile
      target: frankenphp_prod
    environment:
      FRANKENPHP_CONFIG: ''